Description: >

    This template deploys a VPC with public and private subnets spread across
    two Availabilty Zones. It deploys an Internet Gateway and a pair of NAT
    Gateways, with the relevant routes in each of the subnets.

    It then deploys an ECS cluster distributed across multiple Availability Zones. 

    Finally, it deploys a pair of example ECS services from containers published in 
    Amazon EC2 Container Registry (Amazon ECR).

    Last Modified: 7th February 2018
    Author: Paul Lewis <pjlewis@amazon.co.uk>

Resources:

    VPC:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3democloudpipelinestack-s3bucket-j3noarvmx6cw.s3.amazonaws.com/vpc.yaml
            Parameters:
                EnvironmentName:    !Ref AWS::StackName
                PrivateSubnet1CIDR: 10.180.24.0/21
                PrivateSubnet2CIDR: 10.180.32.0/21
                PublicSubnet1CIDR:  10.180.8.0/21
                PublicSubnet2CIDR:  10.180.16.0/21
                VpcCIDR:            10.180.0.0/16

    